export const ongoingProjects = [
  {
    slug: "ongoing/botany-rooftop-bar",
    title: "Botany Rooftop Bar",
    location: "Bengaluru",
    category: "Hospitality",
    status: "Ongoing",
    description: "Perched high above the city skyline, Botany Rooftop Bar is a sultry, high-octane sanctuary where wild botanical maximalism meets theatrical luxury.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092682/WhatsApp_Image_2026-02-23_at_5.53.23_PM_n3rw5y.jpg",
    galleryImages: [
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092677/WhatsApp_Image_2026-02-11_at_1.04.11_PM_1_lhkyil.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092678/WhatsApp_Image_2026-02-11_at_11.06.00_AM_pymwon.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092681/WhatsApp_Image_2026-02-11_at_1.04.11_PM_ywfe9e.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092682/WhatsApp_Image_2026-02-23_at_5.53.23_PM_1_i36rcl.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092682/WhatsApp_Image_2026-02-23_at_5.53.23_PM_n3rw5y.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092683/WhatsApp_Image_2026-02-11_at_1.04.12_PM_kflidl.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092684/WhatsApp_Image_2026-06-08_at_10.25.34_AM_pvavna.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092685/WhatsApp_Image_2026-06-08_at_10.25.35_AM_hlukhl.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092687/WhatsApp_Image_2026-06-08_at_10.25.36_AM_yfaoxd.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092687/WhatsApp_Image_2026-06-08_at_10.25.37_AM_y91znw.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092687/WhatsApp_Image_2026-02-20_at_11.19.05_AM_jakzct.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092688/WhatsApp_Image_2026-02-11_at_11.05.59_AM_1_da6eoq.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092688/WhatsApp_Image_2026-02-11_at_1.04.12_PM_1_al9fiu.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092689/WhatsApp_Image_2026-02-18_at_5.46.04_PM_2_mc4b9p.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092699/WhatsApp_Image_2026-02-11_at_1.04.09_PM_1_aslsud.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092699/WhatsApp_Image_2026-02-11_at_1.04.12_PM_2_odxb00.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092699/WhatsApp_Image_2026-07-28_at_3.36.45_PM_sjvmr3.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092699/WhatsApp_Image_2026-02-11_at_1.04.09_PM_cm5c8s.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092699/WhatsApp_Image_2026-07-15_at_10.47.11_AM_1_fshnmu.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092699/WhatsApp_Image_2026-02-24_at_12.34.14_PM_yb7uoc.jpg" },
    ],
  },
  {
    slug: "ongoing/karnataka-golf-association",
    title: "Karnataka Golf Association",
    location: "Bengaluru",
    category: "Commercial",
    status: "Ongoing",
    description: "A sophisticated transformation of the Karnataka Golf Association into a timeless members' club blending heritage, luxury and contemporary resort-inspired interiors.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786095445/WhatsApp_Image_2025-11-27_at_11.40.36_AM_gwou0h.jpg",
  },
  {
    slug: "ongoing/nagarhole-wilderness-retreat",
    title: "Nagarhole Wilderness Retreat",
    location: "Nagarhole, Mysuru",
    category: "Hospitality",
    status: "Ongoing",
    description: "A luxury eco-resort masterplanned along the edge of Nagarhole National Park, blending sustainable architecture with immersive wilderness experiences.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786096621/cover_photo_gishem.jpg",
  },
  {
    slug: "ongoing/vista-do-mar-apartment",
    title: "Vista Do Mar Apartment",
    location: "Goa",
    category: "Residential",
    status: "Ongoing",
    description: "A boutique luxury residential development designed to celebrate panoramic coastal views, expansive residences and contemporary architecture.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786692550/201_cover_htrs5y.png",
    galleryImages: [
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786692045/200_foycba.png" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786692048/201_oc9jss.png" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786692049/199_dczkmd.png" },
    ],
  },
  {
    slug: "ongoing/shobhit-penthouse",
    title: "Shobhit Penthouse",
    location: "Goa",
    category: "Residential",
    status: "Ongoing",
    description: "Luxury contemporary penthouse designed around openness, tropical living, handcrafted materials and seamless indoor-outdoor spaces.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786098650/COVER_PHOTO_pkeumb.jpg",
  },
  {
    slug: "ongoing/anantapur-residence",
    title: "Anantapur Residence",
    location: "Bengaluru",
    category: "Residential",
    status: "Ongoing",
    description: "A multi-story, modern luxury home that seamlessly balances impressive architectural presence with warm, understated interiors.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092142/COVER_PHOTO_qn4fre.jpg",
    galleryImages: [
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092115/WhatsApp_Image_2026-07-23_at_5.40.40_PM_1_aujkwp.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092116/WhatsApp_Image_2026-07-30_at_5.21.10_PM_2_uy1vb2.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092119/WhatsApp_Image_2026-07-24_at_12.09.03_PM_ymc1wo.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092127/33_fmu6nt.png" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092129/WhatsApp_Image_2026-07-03_at_4.43.20_PM_ss43yb.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092135/WhatsApp_Image_2026-07-03_at_4.43.21_PM_n6g6ao.jpg" },
      { category: "Interior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092137/WhatsApp_Image_2026-07-09_at_4.13.53_PM_2_xjc8tb.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092142/04-EXT_a9gsnc.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786092142/COVER_PHOTO_qn4fre.jpg" },
    ],
  },
  {
    slug: "ongoing/eka-site-development",
    title: "Eka Site Development",
    location: "Bengaluru Rural",
    category: "Residential",
    status: "Ongoing",
    description: "15.6 Acres — A residential community where the landscape becomes the foundation of urban living, with architecture and nature evolving as one interconnected system.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786093364/57_bj8lbr.jpg",
  },
  {
    slug: "ongoing/ekara-resort",
    title: "Ekara Resort",
    location: "Bengaluru Rural",
    category: "Hospitality",
    status: "Ongoing",
    description: "20,000 SQFT — A boutique luxury resort where architecture, landscape and hospitality merge into a seamless tropical retreat.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786095105/COVER_PAGE_fiajuv.jpg",
  },
  {
    slug: "ongoing/lake-view-apartment",
    title: "Lake View Apartment",
    location: "Goa",
    category: "Residential",
    status: "Ongoing",
    description: "A vertical residence that redefines urban family living through generous spatial planning, seamless indoor-outdoor connections, and a refined contemporary material palette.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099077/COVER_PHOTO_fy3rhx.jpg",
    galleryImages: [
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099078/30_lqwzgl.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099077/COVER_PHOTO_fy3rhx.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099073/31_ysknol.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099059/38_oo9q8l.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099036/14a_lzzkkz.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099035/36_jujjjq.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099034/33_dfd968.jpg" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099033/01_MANAS_guinf8.jpg" },
    ],
  },
  {
    slug: "ongoing/marina-residence",
    title: "Marina Residence",
    location: "Nandi Hills, Bengaluru",
    category: "Residential",
    status: "Ongoing",
    description: "A contemporary luxury residence designed around seamless indoor–outdoor living, expansive glazing and landscaped courtyards overlooking the hills of Nandi.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786099484/COVER_PHOTO_yns5qz.jpg",
  },
  {
    slug: "ongoing/kabini-house",
    title: "Kabini House",
    location: "Karnataka",
    category: "Residential",
    status: "Ongoing",
    description: "A sprawling 25-acre residential community along the banks of the Kabini River consisting of 35 luxury villas, each enjoying spectacular waterfront views.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786011466/Screenshot_2026-08-06_153655_hzqhew.png",
    galleryImages: [
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786011467/Screenshot_2026-08-06_154327_vsalli.png" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786011465/Screenshot_2026-08-06_153954_uwhyek.png" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786011464/Screenshot_2026-08-06_154101_r6yz86.png" },
      { category: "Site", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786011463/Screenshot_2026-08-06_153907_bz2kk9.png" },
      { category: "Site", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786011384/Screenshot_2026-08-06_154350_jea2oa.png" },
      { category: "Exterior", src: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786011466/Screenshot_2026-08-06_153655_hzqhew.png" },
    ],
  },
];