export const unbuiltProjects = [
  {
    slug: "mit-manipal-university",
    title: "MIT (Manipal University)",
    location: "Manipal",
    category: "Education",
    description: "The Architecture Faculty of Manipal Institute of Technology has evolved after careful planning as a result of climatic considerations, use of local material, interactive and isolated spaces and zoning. The building aims to set an example of architecture that inspires students to understand the careful inter-relationships between spaces.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786104452/Screenshot_2026-08-07_173401_uald8x.png",
  },
  {
    slug: "mandala-resort",
    title: "Mandala Resort",
    location: "Mysuru",
    category: "Wellness",
    description: "This master plan centers on an eco-luxury wellness sanctuary rooted in organic forms, parametric bamboo structures, and earth architecture. Set against sprawling agrarian landscapes, the project balances grand sacred geometry with grounded, natural materiality.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786103811/COVER_PHOTO_ntbnjf.jpg",
  },
  {
    slug: "etv-embassy-brewery",
    title: "ETV Embassy Brewery",
    location: "Bengaluru",
    category: "Hospitality",
    description: "Designed as an expansive, open-air biophilic oasis, ETV Brewery blends tropical garden aesthetics with warm, organic architectural forms. The design centers on a multi-layered outdoor layout under a striking network of timber tree-canopies with lattice shading, casting dappled natural light across diverse seating zones.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786103109/COVER_PHOTO_rxtzlh.jpg",
  },
  {
    slug: "ambience-park",
    title: "Ambience Park",
    location: "Hyderabad",
    category: "Community",
    description: "Designed as a modern, multi-functional community clubhouse, Ambience Park seamlessly integrates Japandi and Warm Minimalist aesthetics across its wellness, recreation, and dining zones. The design emphasizes fluid movement, tactile earth tones, and organic forms to create a soothing yet vibrant sanctuary for residents.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786102624/COVER_PHOTO_poahpz.jpg",
  },
  {
    slug: "taj-yeshwanthpur",
    title: "Taj Yeshwanthpur",
    location: "Bengaluru",
    category: "Hospitality",
    description: "The proposed interior redesign for the guest rooms and suites at Taj Yeshwanthpur seamlessly blends contemporary modern luxury with subtle, timeless Indian heritage. Designed to offer a warm, restorative sanctuary for both business travelers and leisure guests, the spaces prioritize tactile comfort, functional layout efficiency, and refined aesthetic elegance.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786104785/COVER_PHOTO_f59gow.jpg",
  },
  {
    slug: "bellevue",
    title: "Bellevue",
    location: "Bengaluru Rural",
    category: "Residential",
    description: "Bellevue presents a series of triplex residences structured around clean geometric lines, tactile natural finishes, and a seamless visual flow between indoors and outdoors. The project emphasizes spatial transparency, natural light, and a grounded color palette to cultivate serene, highly functional living spaces.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786105077/COVER_PHOTO_zxqpiu.jpg",
  },
  {
    slug: "hilton-klinx",
    title: "Hilton Klinx",
    location: "Bengaluru",
    category: "Hospitality",
    description: "The space is crafted to offer guests an effortless transition from the everyday to a serene, highly refined sanctuary. From the moment of arrival, the space greets visitors with an understated tactile warmth, as soft, ambient light plays across natural plaster and subtle wood textures.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786105322/COVER_PHOTO_gjylnk.jpg",
  },
  {
    slug: "mercara-house",
    title: "Mercara House",
    location: "Coorg",
    category: "Residential",
    description: "The site is located in Hammiyala Hills around 20 KM from the bustling town of Madikeri. Nestled amidst the Western Ghats, the site enjoys a 360° panoramic view of the surrounding landscape. The objective was to create a home that captures the vastness of the site while providing flexible accommodation for the family and visiting guests.",
    image: "https://res.cloudinary.com/dnyvkptxb/image/upload/v1786105438/COVER_PHOTO_o0be8x.jpg",
  },
];